FROM gcc:13.2 as builder

# Use Bourne-Again Shell
SHELL ["/bin/bash", "-c"]

# Change dir to go to files 
ONBUILD WORKDIR /app

# Copy files
ONBUILD COPY . /app

# Clone Befunge-93 interpreter
ONBUILD RUN git clone https://github.com/catseye/Befunge-93.git

# Change dir to go to files 
ONBUILD WORKDIR /app/Befunge-93

# Compile project
ONBUILD RUN make

# Change dir to go to files 
ONBUILD WORKDIR /app

# run the binary
ONBUILD CMD ["./Befunge-93/bin/bef" , "app/main.bf"]
