---
- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Download and install Vault
  get_url:
    url: "https://releases.hashicorp.com/vault/1.8.0/vault_1.8.0_linux_amd64.zip"
    dest: "/tmp/vault.zip"

- name: Extract Vault
  unarchive:
    src: "/tmp/vault.zip"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Create Vault configuration file
  template:
    src: vault.hcl.j2
    dest: "/etc/vault.hcl"

- name: Start Vault service
  systemd:
    name: vault
    enabled: yes
    state: started
