jenkins:
  systemMessage: "Welcome."
  numExecutors: 2
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        name: "Admin"
        password: "!admin"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
jobs:
  - file: /usr/local/job_dsl.groovy
security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "AcceptFirstConnectionStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
