FROM python:3.10-alpine

# Use Bourne-Again Shell
RUN apk add --no-cache bash

# Use Bourne-Again Shell
SHELL ["/bin/bash", "-c"]

# Copy files
COPY . /app

# Go to folder with files
WORKDIR /app

# Install dependencies
RUN pip install -r requirements.txt

# run app
CMD ["python", "-m", "app"]